### ISSUE TITLE
BHoM_UI: Arrange search results in alphabetical order

### ISSUE THREAD

**Issue by LivAndersson** [BHoM/BHoM_UI#100]
Ensure that, for example, all Environment.Elements.Panel appear in the same order, with no acoustic.panel in between them. Would help overview of components related to own discipline.

![image](https://user-images.githubusercontent.com/42963262/60193567-cfe09e80-982f-11e9-88d7-276642e8007b.png)

**Comment by adecler** [comment]
I am not sure I agree with that issue actually. The results are already sorted based on the likelihood of them being actually what the user is looking for. Within that criteria, things are already sorted alphabetically. So, in your example, an acoustic panel appears between the environment panel because we switch from creating actual object to creating types (which is far less likely to be needed).

Let me know if that make sense and if this issue can therefore be closed or if we need to discuss further.
