### ISSUE TITLE
`CreateRequest` menu is very nested

### ISSUE THREAD

**Issue by epignatelli** [BHoM/BHoM_UI#121]
![image](https://user-images.githubusercontent.com/6352844/64251946-9011f380-cf11-11e9-9e1d-ba52a1ea6b42.png)

**Comment by epignatelli** [comment]
Referencing BHoM/BHoM_Adapter/Issues/78 - to be solve in unison

**Comment by alelom** [comment]
Step 1: reorganize namespaces
Sept 2: create additional case in OraniseItems (BH.Engine.Ui.Compute) to identify the Meethod for CreateFilterRequest and create an OrganiseMethods for that type. OrganiseMethods  should call ShortenBranches (BH.Engine.Data.Modify)

**Comment by alelom** [comment]
As discussed here: https://github.com/BHoM/BHoM_UI/pull/126#issuecomment-528684639

The problem of this is the improper use of FilterRequest in Revit_Toolkit rather than a UI problem.
Once custom Requests are created in Revit_Toolkit, those will live in the Revit namespace, so they will not appear together with the FilterRequest under the Data namespace -- whose menu will collapse one level so FilterRequest will become easily findable.

So the actual issues to be solved in order to avoid this one here are:
* https://github.com/BHoM/Revit_Toolkit/issues/364 --> Revit issue, root cause of this
* https://github.com/BHoM/BHoM/issues/546 --> to avoid misuse of FilterRequest
