### ISSUE TITLE
BHoM_UI : Reflect Defining Property Create Methods into CreateObject menu

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM_UI#124]
Include reflected create method, effectively exposing object initialiser capability for any combination of defining properties.
This has previously been exposed as part of Custom Object - needs to be migrated into  CreateObject menu.

**Comment by al-fisher** [comment]
@adecler perhaps one to work with @alelom in closing out this sprint?
Thanks

**Comment by adecler** [comment]
Perhaps... I am not convinced this should be done on this release. The feature is already here, just not in a place that might be automatically obvious to new users. In comparison, there are features far more important for the quality of life of the user that should be a higher priority than this. First one that comes to mind is the [current description of the methods only showing types for the inputs instead of type and name](https://github.com/BHoM/BHoM_UI/issues/41). 

![image](https://user-images.githubusercontent.com/16853390/64224670-f8a9a200-cf0a-11e9-935e-18e89f572375.png)

**Comment by al-fisher** [comment]
Agree - very important that this issue is closed out with #41 This has also already been flagged for this milestone/sprint. Thanks @adecler 
Also I do think we should prioritise this specific issue for this sprint if we can.
Reason being this will simplify the effort and (importantly) the explanation needed for new contributors to very easily prototype new objects - with zero code required even in engine to get going. Understand functionality in the CustomData menu - however this is not intuitive for new users.

**Comment by epignatelli** [comment]
I have just had some thought about this. From the UI point of view it can be tricky, because the two components store two different type of `SelectedItem`, respectively a `Type` and a `MethodBase` for the `CreateCustom` and the the `CreateObject`.

If this is a problem of UX, it may be solved in a different way.
Here's my proposal:  
A. Rethink the `CreateCustom` component into `CreateBHoMObject` or `BHoMObject`, and let it stay in the `oM` tab of the UIs. You can use this as an object initialiser.  
B. Moving the `CreateObject` component to the `Engine`, which I think it better reflects the underlying `Engine` structure: the component reflects `BH.Engine.*` methods.
C. _[Optional]_ Duplicate the `CreateBHoMObject` component into a `CustomObject` component, that has no feature of forcing the type of the object.


This way we avoid making one component do the job of two, and reduce the friction (recalcitrance?) of the feature implementation.

**Comment by al-fisher** [comment]
#### For the `CreateObject` component. 
This has to remain in the oM menu. 
We simply add an additional menu item into each object type which reflects an item with 1:1 mapping of method aguments and public Properties of the class. 
If implements `IImmutable` obviously ignore.
Picking up on @adecler point [here](https://github.com/BHoM/BHoM_Engine/issues/1155#issuecomment-527727477) on properties inherited from Parents. In addition I would actually expose `name` also coming from the BHoMObject parent, but no others.

Therefore as an example for the Class [Circle](https://github.com/BHoM/BHoM/blob/master/Geometry_oM/Curve/Circle.cs).  
You would get:

`BH.oM.Geometry.Circle.Circle(Point centre, Vector normal, double radius, string name)`

Finally - you should have the option to click plus or minus on these inputs as per the previously implemented CreateCustom. With the properties therefore taking default if not specified or having been removed from the component.


#### For the `CreateCustom` 
I would for now. Leave as is.
Is important that this is also a discrete `button/component` in the menu system. It also has to be in the oM section of the menu.

**Comment by al-fisher** [comment]
@epignatelli @alelom does the above make sense? 😃

**Comment by al-fisher** [comment]
Following chat clarifying intent here - as appreciate @epignatelli your comment above about risks and disadvantages of introducing complexity (i.e a single component `CreateObject` doing two things) from an implementation point of view.

As a goal it is important that:
a) a coder adding a new simple object to the BHoM - should not have to implement a create method or also need to understand the concept of creating typed objects via the CustomObject node - in order to get going. Reduces amount of code that needs to be written and amount of explanation required. 

b) Not having to write a Create method for creating an object just through its public defining properties is equally important for the reason that we would need (and in places currently have) multiple `Create`s exposing different permutations of the public properties. Which is wasted code.

c) a user through the UI - should be able to access all means of creating a type of BHoMObject through the same (`CreateObject`) node. If I what to create a Circle - I should see all available methods for doing so next to each other.
👍

**Comment by epignatelli** [comment]
Hi @al-fisher @alelom ! Logging the technical issues after our call.

There are two main parts of the implementation of the logic:
1. The Grasshopper_UI side of things.
   - The `CreateCustom` allows `+`s and `-`s on the parameters, which means that it must answer to event calls. On the other hand, the `CreateObject` doesn't, and adding this potentially breaks its behaviour. It requires a check, it may be dangerous.
   - The `CreateCustom` only instantiates `Param_ScriptVariable` as grasshopper parameters, and does not specialise them according to the type of the parameter in the backend method (e.g. the `point` variable in `Node(Point point)` will be translated into a `Param_ScriptVariable` instead of `IGeometryParam` - as it happens in the `CreateObject` instead.
   - The way the synchronisation of `InputParams` between Grasshopper and BHoM is solved is different between `CreateCustom` and `CreateObject`. Specifically, `CreateCustom` adds the parameters one by one using the `AddInput` method, whereas `CreateObject` uses the `SetInputParams`, which uses reflection with `MethodInfo.GetParameters()`.

All these differences of behaviour must be merged into one component. It is possibile, but will have a lot of `if` `else` to check if we're following one logic or the other.

2. The BHoM_UI side, `CreateCustomCaller` and the `MethodCaller` (implemented by the `CreateObjectCaller`).
   - The both inherit from the `Caller`, which stores two main things, a `object SelectedItem`, and a `Selector<T> Selector`. The `Selector` is responsible to keep track of what are all the possible choices (e.g. all the `Create` methods), and `SelectedItem` registers the actual user choise (e.g. `Create.Bar`). The type of `SelectedItem` of the `CreateCustomCaller` and `MethodCaller`  are different, respectively `MethodBase` and `Type`.  This means, and __I think this is the main infrastructural issue__, we should have two `Selector<T>`: `TypesSelector<Type>` and `MethodSelector<Type>`.  The alternative is to create a new dynamic syntax  on the fly (like we do with the accessors), because c# does not allow to cannot create `ConstructorInfo`s on the fly. 
   - The have a different implementation of the `Run` method. At the moment, the `CreateCustom` is creating an empty instance of he object and then setting the values of its properties. `CreateObject` is just running the back-end method.

So, I think all of the above is possible (and I am pretty sure that mine is not the best solution). The only problem is that it requires a bit of surgical attention to the changes, because it touches the backbone of the two components.

**Comment by al-fisher** [comment]
Useful and interesting discussions. Thanks @epignatelli @alelom.
Summary. Again. The issue we are hitting is the difference (in the code) between 
- creating a BHoMObject through object _Initialiser syntax_ (using Defining Properties) and 
- creating an object through the _Create methods_ (using Derived or mix of Properties/Inputs)

So three options:

**1. Celebrate the difference in the code** and have two separate components/mechanisms to access. 
i.e. `CreateObject` and `InitialiseObject` - with the later being very similar to the current `CustomObject` component (just making it more obvious and discoverable) Also keeping a Create Custom Object as a separate component focused on the Custom use case.

**2. Auto-generate `Create` methods** based on exposing all Public Properties. 
Can be either at runtime or compile time as is most efficacious.

**3. Handle in the UI** to combine the two modes into a single component (or two different types of components being generated from the same menu selection. Depending on how you look at it)

The options above have implications on clarity of narrative, UX and usability as well as complexity of implementation. 
@epignatelli @alelom @adecler lets pick up tomorrow to consider what is best both long term and immediate term.

**Comment by adecler** [comment]
- I agree with @epignatelli that this will require changes on the UI framework itself (which I don't recommend doing so close to the end of the quarter).
- @al-fisher , I don't like the idea of two components if you are planning on removing most Create methods because it would mean the user having to try the `CreateObject` component and switch to the `InitialiseObject` if no constructor is found there. To me, the best option is to auto-generate the create methods. While on the topic, I would prefer generating them the first time they are needed instead of front loading the whole thing. The BHoM is already slowing down the UI's loading enough as it is.
- The code in CreateCustom is heavily relying on reflection and is therefore a lot less efficient than a regular `Create` method. This means we cannot not just copy-paste that code into `CreateObject` unless you are prepare to take a hit on the creation time of every BHoMObject (once we get rid of most Create methods). It was fine as a niche feature within the CreateCustom but not OK for a 90% use case. 

Happy to tackle this properly at the being of the next quarter but seriously doubtful it should be done now especially when no-one with the required experience in the depth of the BHoM_UI is available to do so.
