### ISSUE TITLE
BHoM_UI: Only show interface method when one matching exists

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_UI#125]
#### Description:

For some context; we ofc currently expose all methods in the UI from the BHoM. For things like geometry where there are one method per object type, this can sometimes lead to a bit of a flood of the UI. For many of these, we have an interface method, a dispatch method, that in turn will call the correctly implemented method.

Question is if it would be good to hide all the actual implementing methods from the UI and only expose the interface method, if and when it exists. As an example for the bounds methods:

![image](https://user-images.githubusercontent.com/22005920/64165513-8d49cc80-ce45-11e9-9523-54345eff1f82.png)

here we would only really need to expose the `Bounds(IGeometry geometry)`. This would significantly decrease the number of methods to search through and make it easier to find the one you need.

Wonder if this could be done on the UI side on startup, if we want to pursue it.

Comments?
@pawelbaran @adecler @al-fisher @rwemay @FraserGreenroyd @epignatelli @alelom

**Comment by FraserGreenroyd** [comment]
My question, does this run the risk of confusing a user who might not understand what an `IGeometry` is, or who might not understand that they can plug their `Point` or `Polyline` into the method and return the same result?

**Comment by alelom** [comment]
I can see some consequences of this:
1. users would expect that `Bounds(IGeometry geometry)` should accept any `IGeometry`, which is not true -- am I wrong?
2. It follows that users will not know what `IGeometry` are actually compatible with `Bounds`, unless exposing a lengthy description in the parameter input

So to me is more about where we prefer to expose the compatible inputs list -- in the parameter description (e.g. hovering in GH) or as multiple choices when selecting the method. Considering also Excel as an UI, I'd prefer it as it is now.

**Comment by IsakNaslundBh** [comment]
If I am generally voted down on this solution, I am ofc fine with that, but to comment on you valid raised concerns, starting with your comment @FraserGreenroyd , which I see as same as your point 2 @alelom :

Grasshopper generally deals with this this way:

![image](https://user-images.githubusercontent.com/22005920/64169405-0e0cc680-ce4e-11e9-92f7-80094cbe2318.png)

If there is a method that accepts any kind of geometry, there is only one of them, not one for each type. This could be solved with being clear in what IGeometry/ICurve/ISurface etc means.

For you point 1 @alelom : If an I-method exists, then at least the method header _should_ exist, but return NotImplemented exception and have a` [NotImplemented]` attribute for the code to be compliant.

Regarding excel, all methods could still potentially be loaded up for the inline formula, and we could have this change only affect the search menu as well as the drop-down.

Again, if this still feels to unclear, lets scrap this idea all in all 👍 

Another argument against the idea is that it means the code and UI are no longer 100% one-to-one, and that in itself might be enough to not do this.

**Comment by FraserGreenroyd** [comment]
Thanks for the clarification @IsakNaslundBh , I am happy to withdraw my concern based on your response because ultimately BHoM will be used by people familiar (hopefully) with GH/Dynamo, so if that's how they handle it then I don't see why we couldn't follow suit.

Obviously the Code/UI not being 1:1 could be a reason against as you so rightly say, but I'll let @adecler comment on that as a framework perspective :smile:

**Comment by alelom** [comment]
Thanks @IsakNaslundBh! I had/have no intent on going against the idea at all, just expressing what the situation seems to be from my point of view  -- I'm actually the least experienced on these things so please forgive me if I say nonsense 😄 

I think I now understood better your idea, and I am inclined to agree with you. As you say, it makes sense to "merge" all those query methods in only one "I-method" if it's doable. 

Couple of other notes:
1. the `NotImplementedException` should express the problem in an easily understandable way, adding some text like:
![image](https://user-images.githubusercontent.com/6352844/64178325-2df5b780-ce59-11e9-94ae-7b25c2e46bf7.png)

2. Whenever it makes sense to do so, the "I-method" should state, through its attributes either on its description or in its inputs, that it does not support all the possible implementations of the Interface. This might not be the case for Bounds (who would use Bounds for a `TransformationMatrix` or a `Quaternion`?) but I'm sure it can apply to others

At the moment I'm unsure how this could be achievable but I'm sure it is.

**Comment by alelom** [comment]
> If there is a method that accepts any kind of geometry, there is only one of them, not one for each type. This could be solved with being clear in what IGeometry/ICurve/ISurface etc means.

Then again, we've reasoned with the `IBounds` query method that supports most (except only 3 or 4) of the `IGeometry` implementations. However, what would happen if we the situation is reversed? 

Consider if we had an "I-method" that actually supports only a minority of all the interface implementations. In that case it would become extremely important to list all the supported types -- otherwise I can see users frustrated with "nothing works". 

I think we might work around this listing _only the supported implementations_ in the input description, instead of having all of them like now (not sure how easily this is achievable though):
![image](https://user-images.githubusercontent.com/6352844/64180223-5337f500-ce5c-11e9-9f28-3ccb864b9d56.png)

But would this work for other UIs?

**Comment by adecler** [comment]
I am not a big fan of that idea either (sorry Isak 😋 ).
Here's a few things that come to (my sleepy) mind:
- I agree with Fraser and Alessio that new users might be ocnfused by seeing only the interface methods. Geometry is an example where interfaces are pretty obvious to anyone so it might not appear as a strong argument here but what if I tell you I have a IStackable interface in DataViz_Toolkit? We would need to add the tooltip listing all possible implementation directly in the menu itself.... Feel like we are increasing complexity instead of reducing it, no?
- I don't buy you argument about GH only offering the interface level if it exists. GH can afford to do that because ALL the implementations of that interface are covered. That's not true for us. You could argue that we only reduce to the interface method when all classes are covered but wwhat if someone create a new class for that interface later? people wold already have created a component.
- When I search (both in the component search and Ctrl-Shift-B) I often something like `Bound circle` and I am certainly not the only one. So the methods need to appear on those two options for sure. Considering that point and the fact that the menu is mainly targeted at beginner trying to see what is available, it makes less sense that the menu is not matching the other options 1 to 1.
- Yes, providing a one-to-one correspondence with what is in the code is very important. Only exposing interfaces add a level of obfuscation for all that are not exposed to the code regularly.
- Eduardo had implemented the feature that you can open the GitHub page showing you the code corresponding to the component. Surely, being redirected to a method body that dynamically dispatch the call is not as helpful (and probably cryptic) than seeing the correct method.
- You also need to consider that offering the specific type of input (instead of an interface) for a component is not jut for the one creating it. Having a clear expected input type is valuable information for someone opening the script later.

Right, I could go one but, at the stage, I feel that it already starts to being mean so I'll stop 😄 . Happy to discuss further if you disagree with all of the above.

**Comment by adecler** [comment]
@IsakNaslundBh , if I remember correctly, we had a chat where you said you agree with my concerns raised above. Should we therefore close this?

**Comment by IsakNaslundBh** [comment]
@adecler Yes, I am fine with us closing this. Agree that the arguments against outweighs the arguments for.
