### ISSUE TITLE
Separate out the methods of the External component from the others in the CTRL + SHIFT + B menu

### ISSUE THREAD

**Issue by epignatelli** [BHoM/BHoM_UI#175]
#### Description:

At the moment when you hit CTRL + SHIFT + B also all the methods harvested from the `*BH.*.Engine.External` class are shown.

They have a different level of testing, thus the provide a different level of confidence to the user. I think it would be better to separate these out into another menu, as it would show to be in a more unsafe land.

This will also push us to migrate/wrap some of the unsafe method into safe land, and give as a measure of the progress of it.

This will be yet more important when we will consolidate them into the `Adapter.Execute` paradigm.

#### Proposed solution:
To have a second menu from where we can access all these methods. CTRL + SHIFT + E ?

@al-fisher @adecler thoughts?

**Comment by adecler** [comment]
I am not sure I agree with that. 
- I already get it wrong too often in GH by double-clicking instead of using Ctrl-Shift-B. Having another separate menu is going to make it even worth. 
- The external methods already have a different icon so they are already appearing with a different highlight than the rest
- things going into the installer should have received a certain level of testing so I am not sure the reason stands
- In the long run, some of the external libraries will be quite robust and properly tested. Using the `External` as a separator is therefore not correlated to the problem you are trying to solve (not that I think it needs solving in my opinion)
