### ISSUE TITLE
BHoM_UI: Property assigment creates for Requests does not show up in CreateRequest component

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_UI#176]
#### Description:

Since enabling property assignment methods in the CreateObejct component, of no more need for generating Create method for requests without any default `Create` methods in the engine.

The CreateRequest needs to be updated to match this behaviour. Right now only Requests with a create method show up there.

#### How to replicate:

Try to create for example a `BarResultRequest` in the CreateRequest component

#### Expected behaviour:

For all proeprty assigment creates for requests to show up in the CreateRequest component

#### Test file(s):

No testfile needed.

**Comment by IsakNaslundBh** [comment]
Putting this in Release 3.0 if it is a quick fix doable safely, if not, feel free to bump to 3.1 as the requests still can be created in the CreateObject component.

**Comment by adecler** [comment]
I am a bit unclear as to why you marked this as a bug and not a feature (other than to be able to still push it this quarter). The ability to create object with a corresponding `Create` method is a new **feature** we have pushed this quarter on the `CreateObject` component and haven't yet followed up with actually deleting existing `Create` methods. 
The change required to also have this working on the `CreateRequest` component is not very difficult but necessitate some refactoring to prevent duplication of code. This is therefore something I am not too comfortable doing so close to the release when I don't see this as a bug that needs fixing.

**Comment by IsakNaslundBh** [comment]
Happy moving it and changing type to feature. And agree, putting it as a bug is a bit of a stretch..

Have changed label and milestone.

**Comment by al-fisher** [comment]
Capturing conversation on email thread here and clarifying the status.

- Any Request still requires an explicit Convert method in its engine in order to be picked up and accessible through the CreateRequest Component. 

- _All_ requests are however discoverable through the standard CreateObject Component and other menu items.

- In advance of close out of this issue - if we want to ease expose of any Request (into CreateRequest) we can in immediate term add an explicit Create method.

- This issue should be closed out as priority 3.2 MVP.

- The last point above in advance of the planned formal migration and removal of all Property based Create methods
