### ISSUE TITLE
BHoM_UI: Versioning Methods Not Read Properly

### ISSUE THREAD

**Issue by kThorsager** [BHoM/BHoM_UI#242]
#### Description:

Some methods which have been through Versioning gets a problem in UI.
Specifically ones were the first input is a collection.

```
1. This component failed to run properly.
- Error: Index was outside the bounds of the array.
- Occured in  BH.UI.Templates.MethodCaller.Run(Object[] inputs)
     called from BH.UI.Templates.Caller.Run()
- Are you sure you have the correct type of inputs? Check their description for more details.
```

recreating the method works fine, but is quite annoying

#### Test file(s):

some file with the issue, haven't dared to save since I saw the issue so there's some other things as well
https://burohappold.sharepoint.com/:f:/s/BHoM/EoFRz8dFG9lApm_MB5k0Y_MBnaunhZP6r9oBM6qXEHcyyw?e=CWyAVM

**Comment by IsakNaslundBh** [comment]
@adecler I digged into this a little bit, and the problem seem to come from the input parameters not having their type serialised in the list correctly.

The inputparams from the json looks like this:

![image](https://user-images.githubusercontent.com/22005920/79454565-bfcac300-7feb-11ea-8114-4205656c71c2.png)

while the one setup automatically by the component looks like this:
![image](https://user-images.githubusercontent.com/22005920/79454607-d113cf80-7feb-11ea-8085-fc7481703dcb.png)


This leads to a crash on line 469, in CreateInput called by the compile input getters, due to lack of generics.:

https://github.com/BHoM/BHoM_UI/blob/f1b7a67a24bdf26d709b81ca161c0d9aa5834b78/BHoM_UI/Templates/Caller.cs#L467-L469

For one of the component, simply commenting out the following lines in Read helped:

https://github.com/BHoM/BHoM_UI/blob/f1b7a67a24bdf26d709b81ca161c0d9aa5834b78/BHoM_UI/Templates/Caller.cs#L324-L331

This is cause the `SetItem` method already ensures the inputs are correct (and it calls the `CompileInputGetters` already and correctly for this case), at least for methods. Saying this, I do not know the implications of simply removing that generally, so would prefer to leave it to you to look at this @adecler .

**Comment by adecler** [comment]
I am starting to think that Methods and Types should be upgraded too when deserialised instead of trying to keep them as the originals. 

The idea was that upgrading an object doesn't change its content, just its form. While this would modify the method/type therefore loosing the original target. 

But this is a clear example of where that logic creates problems: Even if we upgrade InputParam itself it will not upgrade its Type properties. Wich means no fix in the UI side can take care of this issue without changing the serialiser too.

**Comment by adecler** [comment]
@al-fisher, @IsakNaslundBh  , probably worth a quick chat on that one.

**Comment by adecler** [comment]
I tracked the reason why we had the code below to here: https://github.com/BHoM/BHoM_UI/issues/91
https://github.com/BHoM/BHoM_UI/blob/f1b7a67a24bdf26d709b81ca161c0d9aa5834b78/BHoM_UI/Templates/Caller.cs#L324-L331
So, it seems that the only reason this code is there is to take care of the case where the method assigned to the component cannot be found anymore by making sure that the inputs and outputs are kept (and so the wire too). If that's the only useful case, then we might as well limit the execution of that code to that very specific case. So, basically doing something very close to what @IsakNaslundBh suggested :wink:
