### ISSUE TITLE
BHoM_UI: Consistent Explode after overriding properties

### ISSUE THREAD

**Issue by kThorsager** [BHoM/BHoM_UI#277]
#### Description:

Structures recently overrode the name property on for example `Loadcase`. As a result all explode components either jumbled their order or had all their outputs as `null`.
![image](https://user-images.githubusercontent.com/53530468/84017561-bff59800-a976-11ea-8a2a-ecec2719e2e7.png)

#### Expected behaviour:

Since no properties were added or removed it would be better to not brick the explode component to keep the scripts working.

#### Test file(s):

A loadcase connected both to a "old" explode and an updated one.
https://burohappold.sharepoint.com/:u:/s/BHoM/EeUTEBu7PI1OsUZs7SzChPUBN5SvQsWQM9OgLSgRkHONGQ?e=edsmiS

FYI @IsakNaslundBh @adecler @epignatelli

**Comment by adecler** [comment]
Since this can be fixed by the user by upgrading the component from the context menu (as suggested by the warning), I will fix this next quarter.

**Comment by adecler** [comment]
This case only happens if two conditions are met:
- The Explode component is old enough that it was still saved using an old serialisation solution that was different for the Explode component (using `Outputs` and `PossibleOutputs` fields in the json string).
- The component was ran when there was an old bug that was modifying the order of the outputs based on selection/deselection of items in the list of outputs to expose.

This resulted in the outputs on the components not matching the outputs stored in the save file. As you can see the order of the outputs from the saved json is not matching the ones on the Grasshopper component:

![image](https://user-images.githubusercontent.com/16853390/108317686-9d03cf00-71f9-11eb-8c27-2107921acb27.png)

Unfortunately, the corruption of the Grasshopper component not being reflected in the saved data means that it is not possible for the BHoM_UI to fix to problem. It is possible to add code in the Grasshopper toolkit that would be used only to detect and fix this specific case but I believe this is now old enough that it is better to just left it unsolved and simply let the user replace/update the component.
