### ISSUE TITLE
Duplicated input in a ModelLaundry test file component

### ISSUE THREAD

**Issue by LMarkowski** [BHoM/BHoM_UI#303]
#### Description:

While testing environment workflow in ModelLaundry I found a failing component with that error:
![image](https://user-images.githubusercontent.com/48125514/93216511-20f7ed80-f768-11ea-806f-7c53b6247db0.png)
It looks like the first input is duplicated. After placing that same component and plugging extracted inputs everything seems to work fine.
![image](https://user-images.githubusercontent.com/48125514/93217164-f195b080-f768-11ea-948a-c814b139dd23.png)
Duplicated `Location`s are almost identical, but they have different `BHoM_Guid`s.

#### Steps to reproduce:

**Edit:**
Moved failing component to a seperate file [here](https://burohappold.sharepoint.com/:f:/s/BHoM/ElpSxaboDEFDoK2U-MEI6SQBbHrhYo8vpKeqHDDh193HNQ?e=zPCTTE) to clean the Environment ML Workflow test file.
<s>Open BuroHappold_BHoM_v3.3.beta_Environment_ML_BasicWorkFlow.gh file from [here](https://burohappold.sharepoint.com/:f:/s/BHoM/EsqrmErnsJNBhNam7v2RweIBlicmw6jGbhjHYt2OyNDlDg?e=URJbDI)</s>
**/Edit**

@adecler (as it is UI)
@FraserGreenroyd (as it is environment)
@al-fisher (as it happened while testing for foundational)

**Comment by adecler** [comment]
Note: for those wanting test this, the file to download is `BuroHappold_BHoM_v3.3.beta_Environment_ML_BasicWorkflow.gh`, not `BuroHappold_BHoM_v3.3.beta_Structures_ML_BasicWorkFlow.gh`

**Comment by LMarkowski** [comment]
@adecler You're right. I must've copied wrong line, sorry. Updated the description.

**Comment by adecler** [comment]
This component was already in an invalid state when saved in the file:

![image](https://user-images.githubusercontent.com/16853390/93298740-5b27c480-f826-11ea-8f2c-2aa6298e3a87.png)

As you can see the Grasshopper itself already has two `Location` input params even before trying to update itself from the BHoM info. 

The input parameters saved in the json are
- Location
- Location
- Elevation
- Type

So the double `Location` input should fix itself (so, there is a bug there). Note that `Name` input will likely be double once the bug is fixed though since the saved sate of the component was already incorrect.
