### ISSUE TITLE
BHoM_UI: Methods with generics do not function

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_UI#338]
#### Description:

Methods using generic seem to have stopped functioning after some of the later refactoring. Crashing out here in Grasshopper_Toolkit:
![image](https://user-images.githubusercontent.com/22005920/101329654-f2bf1100-3871-11eb-90e8-972c126c3212.png)

Due to not being able to cast (in this example) a `Bar` to an `ILink<INode>` (bar is a `ILink<BH.oM.Structure.Elements.Node>`).

#### Steps to reproduce:

Run a generic method

#### Expected behaviour:

For the component to be able to dynamically set itself to some generic type (including inputs which seem to be the problem now) and then call the method.

#### Test file(s):

https://burohappold.sharepoint.com/:u:/s/BHoM/EXfJUlWvArJIorm_FenLFuQBH4j07uWD4Ahm-VFIOZlRZQ?e=d60no6

**Comment by adecler** [comment]
Transferred since it is actually a BHoM_UI issue.
This is an interesting case: 
- the Grasshopper toolkit has now some of it's exceptions replaced with BHoM events due to those exception needing to be handled locally for usage in the context of GH components.
- The BHoM UI on the other hand was relying on catching a casting Exception to know when to update the input getter on generic types. 

As discussed in other conversation, I think that the solution is to never use Exception but, instead, have a better event system that make it easy to check for new events (based on their type) and even to remove some when needed (in case a second attempt need to be made with alternative parameters for example).

@alelom , @al-fisher , FYI.
