### ISSUE TITLE
Grasshopper data access error introduced with recent change to SetProperty

### ISSUE THREAD

**Issue by michaelhoehn** [BHoM/BHoM_UI#375]
#### Description:

Apologies I didn't get a chance to test prior to the SetProperty updates here https://github.com/BHoM/BHoM_UI/pull/372, but I've found another problem introduced. Seems this is now enforcing a specified data access type rather than allowing that to be determined by the user/objects. 

200217 Alpha (expected behaviour)
![image](https://user-images.githubusercontent.com/54593392/108916907-efc7f700-75fc-11eb-965b-559149fbb585.png)

200223 Alpha (same workflow with sample objects)
![image](https://user-images.githubusercontent.com/54593392/108918072-c0b28500-75fe-11eb-816e-7c1db8f0dd8b.png)

#### Test file(s):

[Test File](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/BHoM_UI/%23375-SetPropertyDataAccess/SetMatProp.gh?csf=1&web=1&e=HLtUWZ)

FYI @enarhi

**Comment by adecler** [comment]
Related to https://github.com/BHoM/Grasshopper_Toolkit/issues/605 and https://github.com/BHoM/BHoM_UI/pull/371.

The specific issue in this one is as follows:
 - The component cannot figure out the type of `Construction.Layers.Material` because `IConstruction` (type of `Floor.Construction`) doesn't have a `Layers` property (see **Additional comments** section in https://github.com/BHoM/BHoM_UI/pull/371)
 - In that case, the input object is used to figure out the type of the property to set by calling `GetProperty`. The problem, here, is that the `Layers` property is actually a list so the `Material` property is returned as a list as well. This messes up the type the component is expecting. 

From a perspective of C#, this use of the `SetProperty` component is wrong on so many levels, I didn't really think about that user case. Unfortunately, we need to accommodate for the Grasshopper mindset as much as possible as I commented in https://github.com/BHoM/BHoM_UI/pull/371. I'll do my best to fix this but I'll need a bit of time to come up with a solution on that one so bear with me.
