### ISSUE TITLE
BHoM_UI: Generic type input parameters specialise against base type erroneously

### ISSUE THREAD

**Issue by awakeman** [BHoM/BHoM_UI#45]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by epignatelli** [comment]
Guys how has this one been fixed at the end? 
I am struggling with the same problem.

**Comment by awakeman** [comment]
Yeah, it was never fixed. Unsure why it's closed.

I was thinking we could defer the call to `MakeGenericType`/`MakeGenericMethod` until run-time (after or during argument capture (CollectInputs)) to specialise on the resulting type.

**Comment by awakeman** [comment]
At least with Generic Parameters, not so easy if the output is specialised only, preventing type inference.

**Comment by epignatelli** [comment]
[`MethodInfo.IsGenericMethodDefinition`](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.methodinfo.isgenericmethoddefinition?view=netframework-3.5) should be able to tell us if the method comes from a generic one, get its generic definition and recompile it with the correct type.

Although, I think it would be very inconvenient to compile the generic method everytime. I'd suggest to specialise it just once, against the collected input, and keep it there.  If you want to use another overload, you'll have to create another component, and specialise that against the new type. 

Related to https://github.com/BHoM/BHoM_Engine/issues/1138

**Comment by adecler** [comment]
Based on archived description from @awakeman , I have created this script:

![image](https://user-images.githubusercontent.com/16853390/72045944-53f10400-32f2-11ea-9593-73b14d60f9c4.png)

Since everything seems to be working fine for that script, can you give an example that doesn't ?

**Comment by epignatelli** [comment]
Something like this would not work:
```c#
        public static int Generic<T>(T input)
        {
            switch (input)
            {
                case int i:
                    return 0;
                case string s:
                    return 1;
                default:
                    throw new System.NotImplementedException();
            }
        }
```

You can find an example in the Numpy_Toolkit with will always throw an exception https://github.com/BHoM/Numpy_Toolkit/blob/master/src/Numpy/Models/Dtype.cs#L35-L81

The latest idea we have discussed was to use the concept of `TypeHint`s when a generic method is encountered. When the user selects a type, the BHoM_UI should recompile the new overload of the method. That way the user is in control of which overload of the generic method to use.

**Comment by adecler** [comment]
Yes, `TypeHint` seems indeed the way to go. I wouldn't have it in the context menu the way GH handles `TypeHint` though. The choices there would either be too limited or the context menu  would be scary big. 

Why not do the same thing as we did for the Dictionary with explicit Type as input?

**Comment by IsakNaslundBh** [comment]
Picking up on this issue after call with @adecler . Have some cases with generics that do not work as expected, for cases with the generic interfaces in Analytical_oM.

#### Some context. 

Many of the interfaces in Analytical_oM contains generics to be able to find a common ground of properties between disciplines, without forcing specific types of sub obejcts in them. For example, and the most complicated case, we have IPanel:

```
namespace BH.oM.Analytical.Elements
{
    public interface IPanel<TEdge, TOpening> : IBHoMObject, IAnalytical
        where TEdge : IEdge
        where TOpening : IOpening<TEdge>
    {
        /***************************************************/
        /**** Properties                                ****/
        /***************************************************/

        List<TEdge> ExternalEdges { get; set; }

        List<TOpening> Openings { get; set; }

        /***************************************************/
    }
}
```

Which basically says that all panels should have edges and openings, but you can pick the type you want yourself.

Now, to be able to write methods accepting any type of panel, we would write something like this (not sure how useful this actual method is, but can be used for test):

```
        public static double PerimiterLength<TEdge,TOpening>(this IPanel<TEdge, TOpening> panel) where TEdge : IEdge where TOpening : IOpening<TEdge>
        {
            return panel.ExternalEdges.Sum(x => x.Curve.ILength());
        }
```

#### Issue

This method can be picked up in c# just fine (able to send in both structural and Env panels to the method), but does not work in the UI.

Currently, adding a component like that to the GH canvas leads to a full Rhino crash. which seemed to stem from some bugs in the `Reflection_Engine`. I added two small fixes to `MakeFromGeneric` and `GenericTypeConstraint`:

```
        public static Type MakeFromGeneric(this Type genericType)
        {
            if (genericType.IsGenericParameter)
            {
                Type[] constrains = genericType.GetGenericParameterConstraints();
                if (constrains.Length == 0)
                    return typeof(object);
                else
                    return MakeFromGeneric(constrains[0]);   //<-- ADDED RECURSIVE CALL HERE
            }
            else if (genericType.ContainsGenericParameters)
            {
                Type[] constrains = genericType.GetGenericArguments().Select(x => MakeFromGeneric(x)).ToArray();
                return genericType.GetGenericTypeDefinition().MakeGenericType(constrains);
            }
            else
                return genericType;
        }
```

and 

```

        public static Type GenericTypeConstraint(this Type type)
        {
            Type constraint = type.GetGenericParameterConstraints().FirstOrDefault();

            if (constraint == null)
                return typeof(object);
            else if (constraint.ContainsGenericParameters)
            {
                 //CHANGE FROM USING TYPE TO USE constraint INSTEAD OR ROW BELOW
                Type[] generics = constraint.GetGenericArguments().Select(x => GenericTypeConstraint(x)).ToArray();
                if (generics.Length == 0)
                    generics = new Type[] { typeof(object) };
                return constraint.GetGenericTypeDefinition().MakeGenericType(generics);
            }
            else
                return constraint;
        }
```

The above stopped the crash, and enabled you to create the component, but, the input type is still wrong, as all the inner generics have been set to their contraint instead of staying generic. This is, for the method to work wee need it to accept 
`IPanel<TEdge, TOpening> ... where TEdge : IEdge where TOpening : IOpening<TEdge>` 
, but in the UI it instead turns it into a method accepting 
`IPanel<IEdge, IOpening<IEdge>>`

and this later part does not fulfil the constraints of a structural or environmental panel. 

#### Conclusion/TL;DR

We need to update the way we handle generics in the UI to keep the constraint of the methods consistent for inputs of methods and components.

Very long wall of text, but wanted to capture what I had done and my conclusions.

**Comment by IsakNaslundBh** [comment]
To add to another problem found with the generics (this is more of a BHoM_Engine issue, but adding to the list here).

The `RunExtensionMethod` method in Reflection_Engine is also failing to pick up methods of the type mentioned in the comment above. 

This seem to come from the Query method `ExtensionMethods(this Type type, string methodName)` not being able to pick up that a sub type is of a generic base type. Basically:

`param[0].ParameterType.IsAssignableFrom(type)` will return false for the case where

`param[0].ParameterType = IPanel<TEdge, TOpening>`

and 
`type = Panel` 

and `Panel :  IPanel<Edge, Opening>`

Hope makes sense..
